---

- name: Copy jmeter Docker image contents
  copy:
    src: "opt/3scale-perftest/jmeter-image-contents"
    dest: "{{ injector_root_path }}/"
  register: jmeter_docker_img

- name: Build injector Docker image
  docker_image:
    path: "{{ injector_jmeter_image_contents_path }}"
    state: present
    name: "{{ injector_jmeter_image_name }}"
    tag: "{{ injector_jmeter_image_tag }}"
    force: "{{ jmeter_docker_img.changed }}"
