# tasks file for profiled-traffic-generator
---
- name: Creates tmp traffic directory
  tempfile:
    state: directory
  register: tempdir_1

- name: Run Buddhi to create traffic file
  docker_container:
    name: buddhi
    state: started
    user: root
    tty: True
    detach: no
    image: quay.io/3scale/perftest-toolkit:v2.3.0
    command: "perftest-toolkit-buddhi --portal {{ threescale_portal_endpoint }} --profile \"{{ traffic_profile }}\" --public-base-url \"{{ public_base_url }}\" --private-base-url \"{{ private_base_url }}\" -o /traffic/traffic.csv"
    volumes:
      - "{{ tempdir_1.path }}:/traffic:z"
    env:
      THREADS_N: "5"

- name: Copy traffic file
  copy:
    src: "{{ tempdir_1.path }}/traffic.csv"
    dest: "{{csv_file_path}}/{{csv_file_name}}"
    remote_src: true

- name: Remove the temporary file
  file:
    path: "{{ tempdir_1.path }}"
    state: absent
  when: tempdir_1.path is defined
