---
# tasks file for user-traffic-reader
- name: Creates tmp traffic directory
  tempfile:
    state: directory
  register: tempdir_1

- name: Creates traffic directory
  file:
    path: "{{ injector_traffic_path }}"
    state: directory

- name: Run Buddhi to create traffic file
  docker_container:
    name: buddhi
    state: started
    user: root
    tty: True
    detach: no
    image: quay.io/3scale/perftest-toolkit:master
    command: "--portal {{ threescale_portal_endpoint }} --services \"{{ threescale_services }}\" -o /traffic/traffic.csv"
    volumes:
      - "{{ tempdir_1.path }}:/traffic"

- name: Copy traffic file
  copy:
    src: "{{ tempdir_1.path }}/traffic.csv"
    dest: "{{ injector_traffic_path }}/csv_traffic_profile.csv"
    remote_src: true

- name: Remove the temporary file
  file:
    path: "{{ tempdir_1.path }}"
    state: absent
  when: tempdir_1.path is defined
