- hosts: 
  - hyperfoil_agent
  roles:
  - hyperfoil.hyperfoil_test
  vars:
    test_name: 3scale-benchmark
- hosts:
  - hyperfoil_controller
  tasks:
  - name: Debug the RunID fact
    debug: var=test_runid
#  - name: Process the run to generate a report
#    shell: "{{ JDK_11_FOLDER }}/bin/java -jar {{ REPORT_HOME }}/target/{{ REPORTER_JAR }} -s /tmp/hyperfoil/workspace/run/{{ test_runid }} -d /tmp/hyperfoil/workspace/run/{{ test_runid }}/index.html"
