# role task file for hyperfoil_generate_report
---
- name: Reports directory
  file:
    state: directory
    path: "{{ reports_path }}"
    recurse: yes
    mode: '0755'
- name: Retrieve the report
  get_url:
    url: "http://{{ hyperfoil_controller_host }}:{{ hyperfoil_controller_port }}/run/{{ test_runid }}/report"
    dest: "{{ reports_path }}/{{ test_runid }}.html"
