# role task file for hyperfoil_generate_report
---
  - name: Creates tmp report directory
    tempfile:
      state: directory
    register: tempdir_report
  - name: Creates reports directory
    file:
      state: directory
      path: /opt/3scale-perftest/reports
      recurse: yes
      mode: '0755'
  - name: Copy report tool
    copy:
      src: "{{ playbook_dir }}/files/report.sh"
      dest: "{{ tempdir_report.path }}/"
      mode: 'preserve'
  - name: Retrieve the run data
    get_url:
      url: "http://{{ hyperfoil_controller_host }}:{{ hyperfoil_controller_port }}/run/{{ test_runid }}/stats/all"
      headers:
        Accept: 'application/json'
      dest: "{{ tempdir_report.path }}/{{ test_runid }}-all.json"
  - name: Creates hyperfoil report
    shell: "cat {{ tempdir_report.path }}/{{ test_runid }}-all.json | docker run -i --rm quay.io/hyperfoil/hyperfoil-report /opt/report.sh > /opt/3scale-perftest/reports/index-{{ test_runid }}.html"
  - name: Remove the tmp report directory
    file:
      path: "{{ tempdir_report.path }}"
      state: absent
    when: tempdir_report.path is defined
