plugin: 3scale_inventory_plugin

- hosts:
  - hyperfoil_controller
  - hyperfoil_agent
  tasks:
  - include_role:
      name: injector-configurator
- hosts:
  - hyperfoil_controller
  roles:
  - injector_setup
- hosts: 
  - hyperfoil_agent
  roles:
  - injector
  vars:
    test_name: 3scale-benchmark
- hosts:
  - hyperfoil_controller
  roles:
  - hyperfoil.hyperfoil_shutdown
