- hosts:
    - hyperfoil_controller
    - hyperfoil_agent
  tasks:
  - include_role:
    name: injector-configurator
- hosts: 
    - hyperfoil_controller
    - hyperfoil_agent
  tasks:
    - name: Assign path variable
      set_fact:
        csv_dest_file_path: "/tmp/{{ csv_file_name }}"
    - name: Distribute CSV inventory source file
      copy:
        src: "{{ csv_file_path }}/{{ csv_file_name }}"
        dest: "{{ csv_dest_file_path }}"
        force: yes
- hosts: hyperfoil_controller
  tasks:
  - include_role:
      name: injector-setup
- hosts: hyperfoil_controller
  tasks: 
  - include_role:
      name: hyperfoil.hyperfoil_test
    vars:
      test_name: 3scale-benchmark
#- hosts: hyperfoil_controller
#  tasks:
#  - include_role:
#      name: hyperfoil.hyperfoil_shutdown
