---
- hosts:
    - hyperfoil_controller
    - hyperfoil_agent
  tasks:
  - include_role:
      name: platform-setup
  become: yes
- hosts:
    - hyperfoil_controller
  tasks:
  - include_role:
      name: profiled-traffic-generator
- hosts:
    - hyperfoil_controller
  tasks:
  - include_role:
      name: traffic-retriever
- hosts:
    - hyperfoil_controller
    - hyperfoil_agent
  tasks:
  - include_role:
      name: traffic-distributor
- hosts: hyperfoil_controller
  tasks:
  - include_role:
      name: injector-setup
