---
- hosts: hyperfoil_controller
  tasks:
  - include_role:
      name: hyperfoil.hyperfoil_test
    vars:
      test_name: 3scale-benchmark
      test_files:
      - "{{ csv_file_path }}/{{ csv_file_name }}"
- hosts: hyperfoil_controller
  tasks:
  - include_role:
      name: hyperfoil_generate_report
