require 'amp/toolkit/buddhi/profiles/register'
require 'amp/toolkit/buddhi/profiles/simple'
require 'amp/toolkit/buddhi/profiles/backend'
require 'amp/toolkit/buddhi/profiles/multiservice'
require 'amp/toolkit/buddhi/profiles/medium'
require 'amp/toolkit/buddhi/profiles/standard'
