---
  - name: Set the hyperfoil controller host variable
    set_fact:
      hyperfoil_controller_host: "{{ groups[hyperfoil_controller_group][0] }}"
  - name: Check Controller status
    uri:
      url: "http://{{ hyperfoil_controller_host }}:{{ hyperfoil_controller_port }}/"
    register: hfc_status
    ignore_errors: True
  - name: Start Controller
    when: hfc_status.status == -1
    include_role:
      name: hyperfoil.hyperfoil_setup
    vars:
      hyperfoil_controller_args: "-Dio.hyperfoil.deploy.timeout=30000 -Dio.hyperfoil.controller.cluster.ip={{ hyperfoil_controller_host }}"
