---
# defaults file for injector-configurator
#
injector_root_path: "/opt/3scale-perftest"
injector_bin_path: "{{ injector_root_path }}/bin"
injector_reports_path: "{{ injector_root_path }}/reports"
injector_plans_path: "{{ injector_root_path }}/test-plans"
injector_traffic_path: "{{ injector_root_path }}/traffic"
injector_plan_file: "{{ injector_plans_path }}/test-plan.jmx"

injector_jmeter_plan_path: "/opt/apache-jmeter-3.1"
injector_jmeter_plan_file: "{{ injector_jmeter_plan_path }}/test-plan.jmx"
injector_jmeter_traffic_path: "{{ injector_jmeter_plan_path}}/data"

injector_traffic_num_lines: 100000

injector_jmeter_image_contents_path: "{{ injector_root_path }}/jmeter-image-contents"
injector_jmeter_image_name: "jmeter-benchmark"
injector_jmeter_image_tag: "1.0"

injector_jmeter_target_host: "<jmeter_target_host>"
injector_jmeter_protocol: "http"
injector_jmeter_target_port: "80"
