# variables file for group_vars
---
csv_file_path: /tmp
csv_file_name: 3scale.csv
reports_path: /tmp/3scale-perftest/reports
csv_dest_file_path: "{{ csv_file_path }}/{{ csv_file_name }}"
toolkit_csv_file_path: benchmarks
locust_csv_file_path: locust
injector_target_group: injector_target
hyperfoil_agent_port: 22
hyperfoil_controller_port: 8090
hyperfoil_agent_group: hyperfoil_agent
hyperfoil_controller_group: hyperfoil_controller
injector_hyperfoil_agent_threads: 4
injector_hyperfoil_target_protocol: https
injector_hyperfoil_target_port: 443
hyperfoil_version: 0.23
