# variables file for group_vars
---

RPS: Maximum requests per second to send
DURATION: Duration of the performance test in seconds
CONCURRENCY: Number of parallel threads to use

shared_connections: "{{ CONCURRENCY }}"

ramp_up_target_users_per_sec: "{{ RPS }}"
ramp_up_duration_sec: 1

csv_file_path: /tmp
csv_file_name: 3scale.csv

toolkit_csv_file_path: benchmarks

steady_state_users: "{{ RPS }}"
steady_state_duration: "{{ DURATION }}"

ramp_down_users: "{{ RPS }}"
ramp_down_duration: 1

hyperfoil_controller_port: 8090

hyperfoil_agent_group: hyperfoil_agent
hyperfoil_agent_port: 22

injector_target_group: injector_target
injector_hyperfoil_target_protocol: https
injector_hyperfoil_target_port: 443

hyperfoil_controller_group: hyperfoil_controller

hf_version: 0.9

injector_hyperfoil_agent_threads: 4
