# role tasks file for platform-setup
---
- name: Load platform package names
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
- name: Install Java
  package:
    name: "{{ java_package }}"
    state: present
- name: Install unzip
  package:
    name: "{{ unzip_package }}"
    state: present
